// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package fastpath

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type bpfPeerKey struct {
	_      structs.HostLayout
	Source uint32
	Ip     uint32
}

type bpfRuleKey struct {
	_        structs.HostLayout
	UpSeid   uint64
	Revision uint64
	Source   uint32
	Teid     uint32
}

type bpfRuleValue struct {
	_              structs.HostLayout
	EgressIfindex  uint32
	SourceIp       uint32
	DestinationIp  uint32
	Teid           uint32
	SourceMac      [6]uint8
	DestinationMac [6]uint8
	UrrCount       uint32
	UrrIds         [4]uint32
	Reserved       uint32
}

type bpfSideConfiguration struct {
	_       structs.HostLayout
	LocalIp uint32
	Flags   uint32
}

type bpfTunnelKey struct {
	_      structs.HostLayout
	Source uint32
	Teid   uint32
}

type bpfUsageKey struct {
	_        structs.HostLayout
	UpSeid   uint64
	UrrId    uint32
	Reserved uint32
}

type bpfUsageValue struct {
	_               structs.HostLayout
	UplinkPackets   uint64
	DownlinkPackets uint64
	UplinkBytes     uint64
	DownlinkBytes   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	bpfMapActiveRevisions    = "active_revisions"
	bpfMapAllowedPeers       = "allowed_peers"
	bpfMapCounters           = "counters"
	bpfMapLatencyBuckets     = "latency_buckets"
	bpfMapPacketRules        = "packet_rules"
	bpfMapSideConfigurations = "side_configurations"
	bpfMapTunnelSessions     = "tunnel_sessions"
	bpfMapUsageCounters      = "usage_counters"
	bpfProgSgwuAccessIngress = "sgwu_access_ingress"
	bpfProgSgwuCoreIngress   = "sgwu_core_ingress"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	SgwuAccessIngress *ebpf.ProgramSpec `ebpf:"sgwu_access_ingress"`
	SgwuCoreIngress   *ebpf.ProgramSpec `ebpf:"sgwu_core_ingress"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveRevisions    *ebpf.MapSpec `ebpf:"active_revisions"`
	AllowedPeers       *ebpf.MapSpec `ebpf:"allowed_peers"`
	Counters           *ebpf.MapSpec `ebpf:"counters"`
	LatencyBuckets     *ebpf.MapSpec `ebpf:"latency_buckets"`
	PacketRules        *ebpf.MapSpec `ebpf:"packet_rules"`
	SideConfigurations *ebpf.MapSpec `ebpf:"side_configurations"`
	TunnelSessions     *ebpf.MapSpec `ebpf:"tunnel_sessions"`
	UsageCounters      *ebpf.MapSpec `ebpf:"usage_counters"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveRevisions    *ebpf.Map `ebpf:"active_revisions"`
	AllowedPeers       *ebpf.Map `ebpf:"allowed_peers"`
	Counters           *ebpf.Map `ebpf:"counters"`
	LatencyBuckets     *ebpf.Map `ebpf:"latency_buckets"`
	PacketRules        *ebpf.Map `ebpf:"packet_rules"`
	SideConfigurations *ebpf.Map `ebpf:"side_configurations"`
	TunnelSessions     *ebpf.Map `ebpf:"tunnel_sessions"`
	UsageCounters      *ebpf.Map `ebpf:"usage_counters"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveRevisions,
		m.AllowedPeers,
		m.Counters,
		m.LatencyBuckets,
		m.PacketRules,
		m.SideConfigurations,
		m.TunnelSessions,
		m.UsageCounters,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	SgwuAccessIngress *ebpf.Program `ebpf:"sgwu_access_ingress"`
	SgwuCoreIngress   *ebpf.Program `ebpf:"sgwu_core_ingress"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.SgwuAccessIngress,
		p.SgwuCoreIngress,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
