// Code generated by bpf2go; DO NOT EDIT.
//go:build (mips || mips64 || ppc64 || s390x) && linux

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pgwupolicyFilterKey struct {
	_         structs.HostLayout
	UeIp      uint32
	Index     uint16
	Direction uint8
	Reserved  uint8
}

type pgwupolicyFilterValue struct {
	_              structs.HostLayout
	LocalAddress   uint32
	LocalMask      uint32
	RemoteAddress  uint32
	RemoteMask     uint32
	LocalPortLow   uint16
	LocalPortHigh  uint16
	RemotePortLow  uint16
	RemotePortHigh uint16
	Precedence     uint32
	PdrId          uint16
	Protocol       uint8
	Tos            uint8
	TosMask        uint8
	Flags          uint8
	Reserved       uint16
}

type pgwupolicyFragmentKey struct {
	_              structs.HostLayout
	UeIp           uint32
	RemoteIp       uint32
	Identification uint16
	Protocol       uint8
	Direction      uint8
}

type pgwupolicyFragmentValue struct {
	_        structs.HostLayout
	Revision uint64
	LastNs   uint64
	Bearer   uint8
	Reserved [7]uint8
}

type pgwupolicyPolicyValue struct {
	_                   structs.HostLayout
	UpSeid              uint64
	Revision            uint64
	BurstNs             uint64
	Rates               [4]uint64
	Capacities          [4]uint64
	QerIds              [2]uint32
	UrrIds              [2]uint32
	UplinkFilterCount   uint16
	DownlinkFilterCount uint16
	GateFlags           uint8
	HasQci1             uint8
	Reserved            uint16
}

type pgwupolicyRateKey struct {
	_         structs.HostLayout
	UeIp      uint32
	Bearer    uint8
	Direction uint8
	Reserved  uint16
}

type pgwupolicyRateValue struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	Reserved uint32
	Revision uint64
	QerId    uint64
	Rate     uint64
	Capacity uint64
	Tokens   uint64
	LastNs   uint64
}

type pgwupolicyUsageKey struct {
	_        structs.HostLayout
	UpSeid   uint64
	Revision uint64
	QerId    uint32
	UrrId    uint32
}

type pgwupolicyUsageValue struct {
	_               structs.HostLayout
	UplinkPackets   uint64
	UplinkBytes     uint64
	DownlinkPackets uint64
	DownlinkBytes   uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	pgwupolicyMapActiveRevisions     = "active_revisions"
	pgwupolicyMapCounters            = "counters"
	pgwupolicyMapFragmentDecisions   = "fragment_decisions"
	pgwupolicyMapPolicies            = "policies"
	pgwupolicyMapRateStates          = "rate_states"
	pgwupolicyMapTftFilters          = "tft_filters"
	pgwupolicyMapUsageCounters       = "usage_counters"
	pgwupolicyProgPgwuDefaultEgress  = "pgwu_default_egress"
	pgwupolicyProgPgwuDefaultIngress = "pgwu_default_ingress"
	pgwupolicyProgPgwuQci1Egress     = "pgwu_qci1_egress"
	pgwupolicyProgPgwuQci1Ingress    = "pgwu_qci1_ingress"
)

// loadPgwupolicy returns the embedded CollectionSpec for pgwupolicy.
func loadPgwupolicy() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PgwupolicyBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pgwupolicy: %w", err)
	}

	return spec, err
}

// loadPgwupolicyObjects loads pgwupolicy and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pgwupolicyObjects
//	*pgwupolicyPrograms
//	*pgwupolicyMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPgwupolicyObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadPgwupolicy()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pgwupolicySpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgwupolicySpecs struct {
	pgwupolicyProgramSpecs
	pgwupolicyMapSpecs
	pgwupolicyVariableSpecs
}

// pgwupolicyProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgwupolicyProgramSpecs struct {
	PgwuDefaultEgress  *ebpf.ProgramSpec `ebpf:"pgwu_default_egress"`
	PgwuDefaultIngress *ebpf.ProgramSpec `ebpf:"pgwu_default_ingress"`
	PgwuQci1Egress     *ebpf.ProgramSpec `ebpf:"pgwu_qci1_egress"`
	PgwuQci1Ingress    *ebpf.ProgramSpec `ebpf:"pgwu_qci1_ingress"`
}

// pgwupolicyMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgwupolicyMapSpecs struct {
	ActiveRevisions   *ebpf.MapSpec `ebpf:"active_revisions"`
	Counters          *ebpf.MapSpec `ebpf:"counters"`
	FragmentDecisions *ebpf.MapSpec `ebpf:"fragment_decisions"`
	Policies          *ebpf.MapSpec `ebpf:"policies"`
	RateStates        *ebpf.MapSpec `ebpf:"rate_states"`
	TftFilters        *ebpf.MapSpec `ebpf:"tft_filters"`
	UsageCounters     *ebpf.MapSpec `ebpf:"usage_counters"`
}

// pgwupolicyVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pgwupolicyVariableSpecs struct {
}

// pgwupolicyObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPgwupolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgwupolicyObjects struct {
	pgwupolicyPrograms
	pgwupolicyMaps
	pgwupolicyVariables
}

func (o *pgwupolicyObjects) Close() error {
	return _PgwupolicyClose(
		&o.pgwupolicyPrograms,
		&o.pgwupolicyMaps,
	)
}

// pgwupolicyMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPgwupolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgwupolicyMaps struct {
	ActiveRevisions   *ebpf.Map `ebpf:"active_revisions"`
	Counters          *ebpf.Map `ebpf:"counters"`
	FragmentDecisions *ebpf.Map `ebpf:"fragment_decisions"`
	Policies          *ebpf.Map `ebpf:"policies"`
	RateStates        *ebpf.Map `ebpf:"rate_states"`
	TftFilters        *ebpf.Map `ebpf:"tft_filters"`
	UsageCounters     *ebpf.Map `ebpf:"usage_counters"`
}

func (m *pgwupolicyMaps) Close() error {
	return _PgwupolicyClose(
		m.ActiveRevisions,
		m.Counters,
		m.FragmentDecisions,
		m.Policies,
		m.RateStates,
		m.TftFilters,
		m.UsageCounters,
	)
}

// pgwupolicyVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPgwupolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgwupolicyVariables struct {
}

// pgwupolicyPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPgwupolicyObjects or ebpf.CollectionSpec.LoadAndAssign.
type pgwupolicyPrograms struct {
	PgwuDefaultEgress  *ebpf.Program `ebpf:"pgwu_default_egress"`
	PgwuDefaultIngress *ebpf.Program `ebpf:"pgwu_default_ingress"`
	PgwuQci1Egress     *ebpf.Program `ebpf:"pgwu_qci1_egress"`
	PgwuQci1Ingress    *ebpf.Program `ebpf:"pgwu_qci1_ingress"`
}

func (p *pgwupolicyPrograms) Close() error {
	return _PgwupolicyClose(
		p.PgwuDefaultEgress,
		p.PgwuDefaultIngress,
		p.PgwuQci1Egress,
		p.PgwuQci1Ingress,
	)
}

func _PgwupolicyClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pgwupolicy_bpfeb.o
var _PgwupolicyBytes []byte
